apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-dyna-demo
  labels:
    app: gke-dyna-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-dyna-demo
  template:
    metadata:
      labels:
        app: gke-dyna-demo
    spec:
      containers:
        - name: gke-dyna-demo
          image: us-east1-docker.pkg.dev/gke-dyna-proj-1/docker-repo/gke-dyna-demo-img:1.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: app-config
              mountPath: /app/config
              readOnly: true
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "768Mi"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 36        # allows up to 3 minutes to start
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: app-config
          configMap:
            name: gke-dyna-demo-config